### ISSUE TITLE
Source of embeds

### ISSUE THREAD

**Issue by jenetiks** [nodauf/Swego#12]
After removing the embedded files from `/src/assets/embedded/`    the files are still being served even with a new session and restarting server. Did searches for "embed" and found a ton of instances but nothing clearly serving these files after removal. I know there is a release without the embeds; however, I was wondering if you could point me towards what is continually serving these files. I'm more interested in replacing than just removing.

Thank you & sorry for being a nub.

**Comment by nodauf** [comment]
Sure,
Do you run with `go run src/webserver.go` or did you build it (and how) ?

**Comment by jenetiks** [comment]
built following wiki exactly, customized yaml config (ip, port, un, pw, directories). Only one edit in the Makefile and that was commenting out the 386 check as it was causing issues. Built fine after doing that.

**Comment by nodauf** [comment]
I did some modification. Could you try:
```sh
git clone https://github.com/nodauf/Swego.git
cd Swego/src
rm assets/embedded/*
make
```

**Comment by jenetiks** [comment]
So I saw the changes that were made to the embedded.go file. Could you elaborate a bit on how/why that would fix the persistent files?

**Comment by nodauf** [comment]
I am not sure to following you.
The change is just to fix a visual issue where / was displaying when the folder was empty.

I change the Makefile as the build section was missing the static files.

**Comment by jenetiks** [comment]
so after removing the files from `src/assets/embedded` (before a fresh clone/make), the files were still being served by the webserver, and were available for retrieval. That's the part im confused with. It was as if they were cached somewhere but I was unable to locate that cache.

Phyiscally, the folder 'src/assets/embedded' was empty, but the files were still being made available

**Comment by nodauf** [comment]
There is no cache. The files are inside the binary.

**Comment by jenetiks** [comment]
Ah okay. That makes more sense than a phantom cache. 

Thanks for your timeliness and responses
