### ISSUE TITLE
Wrong directory

### ISSUE THREAD

**Issue by ddavies1972** [nodauf/Swego#2]
Hi,

Thanks for a great project.

If I start Swego without any parameters the shared directory seems wrong:

```
└─# ./webserver-linux-amd64  
Sharing /usr/local/share/Swego/src/bin/usr/local/share/Swego/src/bin on 0.0.0.0:8080 ...
Sharing private /usr/local/share/Swego/src/bin/usr/local/share/Swego/src/bin/private on 0.0.0.0:8080 ...
```
The shared directory should be /usr/local/share/Swego/src/bin. It seems to be repeated twice.

Regards

Darren

**Comment by nodauf** [comment]
Thank you for the feedback.
The version is still in beta you may find some bugs.

I have fixed the issue, could you please confirm with the new release [v0.8](https://github.com/nodauf/Swego/releases/tag/v0.8)

**Comment by ddavies1972** [comment]
works fine now.

**Comment by nodauf** [comment]
Thanks again for the feedback. Feel free to suggest any feature you want

**Comment by ddavies1972** [comment]
A feature that I'd like is to optionally disable directory listing to make it more private when necessary.
