### ISSUE TITLE
Basic authentication does not work

### ISSUE THREAD

**Issue by belveruski** [nodauf/Swego#41]
Hi,

When i run the following command:
```bash
$ swego web --private test --username test --password test
```
and i go to http://localhost:8080/ or http://localhost:8080/test no basic authentication.

**Comment by nodauf** [comment]
Hi,
The basic authentication will always be on http://.../private.
So you can run:
```
swego web --private test --username test --password test --root public
```
When I have a little more free time, I plan to rewrite this project to make it cleaner and easier to understand. In the meantime, feel free to ask questions or request features.

**Comment by belveruski** [comment]
Hi,
Ah ok I understand better, thank you for this explanation and for these very practical tools.
